RiskManagement/Models/CustomerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RiskManagement.Models
{
    public class CustomerViewModel
    {
        public int Id { get; set; }

        public int NumbetOfBetting { get; set; }

        public int NumbetOfWin { get; set; }

        public int TotalWin { get; set; }

        public int TotalStake { get; set; }
    }
}

RiskManagement/Models/RiskViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RiskManagement.Models
{
    public class RiskViewModel
    {
        public int CustomerId { get; set; }

        public int EventId { get; set; }

        public int ParticipantId { get; set; }

        public int Stake { get; set; }

        public int Amount { get; set; }


        public bool CanWonLargeAmount { get; set; }

        public bool IsRisky { get; set; }

        public bool IsUnusual { get; set; }

        public bool IsHighlyUnusual { get; set; }
    }
}

RiskManagement/Controllers/CustomerController.cs
using Autofac.Extras.Attributed;
using AutoMapper;
using RiskManagement.DataModel;
using RiskManagement.Interfaces.Controllers;
using RiskManagement.Interfaces.Repositories;
using RiskManagement.Models;
using RiskManagement.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RiskManagement.Extensions;
using RiskManagement.Interfaces.Services;

namespace RiskManagement.Controllers
{
    /// <summary>
    /// Implementing ICustomerController for mocking in test
    /// </summary>
    public class CustomerController : Controller, ICustomerController
    {
        private readonly IResultService _resultService;

        public CustomerController(IResultService resultService)
        {
            _resultService = resultService;
        }

        public ActionResult Index()
        {
            var data = _resultService.FindUnusualCustomer();
            var model = Mapper.Map<List<CustomerViewModel>>(data);

            return View(model);
        }

    }
}

RiskManagement/Controllers/RiskController.cs
using Autofac.Extras.Attributed;
using AutoMapper;
using RiskManagement.DataModel;
using RiskManagement.Interfaces.Controllers;
using RiskManagement.Interfaces.Repositories;
using RiskManagement.Models;
using RiskManagement.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RiskManagement.Extensions;
using RiskManagement.Interfaces.Services;

namespace RiskManagement.Controllers
{
    public class RiskController : Controller, IRiskController
    {
        private readonly IRiskService _riskService;

        public RiskController(IRiskService riskService)
        {
            _riskService = riskService;
        }

        public ActionResult Index()
        {
            var data = _riskService.CalculatingRisk();
            var model = Mapper.Map<List<RiskViewModel>>(data);

            return View(model);
        }
    }
}

RiskManagement/Views/Customer/Index.cshtml
@model List<RiskManagement.Models.CustomerViewModel>
@{
    ViewBag.Title = "UnusualWins";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Unusual Rate Wins</h2>

<table class="table">
    <thead>
        <tr>
            <th>Customer</th>
            <th>Number Of Betting</th>
            <th>Number Of Win</th>
            <th>Total Stake</th>
            <th>Total Win</th>
        </tr>
    </thead>
    @foreach (var bet in Model)
    {
        <tr>
            <td>@bet.Id</td>
            <td>@bet.NumbetOfBetting</td>
            <td>@bet.NumbetOfWin</td>
            <td>@bet.TotalStake</td>
            <td>@bet.TotalWin</td>
        </tr>
    }
</table>

RiskManagement/Views/Risk/Index.cshtml
@model List<RiskManagement.Models.RiskViewModel>
@{
    ViewBag.Title = "UnusualWins";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Unusual Rate Wins</h2>

<table class="table">
    <thead>
        <tr>
            <th>Customer</th>
            <th>Event</th>
            <th>Stake</th>
            <th>to Win</th>
            <th>Risky</th>
            <th>Unusual</th>
            <th>Highly Unusual</th>
            <th>Can Win Large Money</th>
        </tr>
    </thead>
    @foreach (var risk in Model)
    {
        <tr>
            <td>@risk.CustomerId</td>
            <td>@risk.EventId</td>
            <td>@risk.Stake</td>
            <td>@risk.Amount</td>
            <td class='@(risk.IsRisky ? "risky" : "")'>@risk.IsRisky</td>
            <td class='@(risk.IsUnusual ? "unusual" : "")'>@risk.IsUnusual</td>
            <td class='@(risk.IsHighlyUnusual ? "higly" : "")'>@risk.IsHighlyUnusual</td>
            <td class='@(risk.CanWonLargeAmount ? "largeMoney" : "")'>@risk.CanWonLargeAmount</td>
        </tr>
    }
</table>

RiskManagement/Views/Shared/_Layout.cshtml
@using System.Web.Optimization

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">

            </div>
            <div class="float-right">
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Unusual Customer", "Index", "Customer")</li>
                        <li>@Html.ActionLink("Risk", "Index", "Risk")</li>                        
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - RiskManagemnet - TechChallenge</p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>